version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - topeducation1
      - topeducation2
  java_db:
    container_name: java_db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Preuniversitario
  topeducation1:
    container_name: java_app1
    image: cmoragalaz/webapp:latest
    build: .
    ports:
      - 8091:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/Preuniversitario
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - java_db
  topeducation2:
    container_name: java_app2
    image: cmoragalaz/webapp:latest
    build: .
    ports:
      - 8092:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/Preuniversitario
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - java_db